### ISSUE TITLE
use everywhere BigInteger instead Integer

### ISSUE THREAD

**Issue by schneidermichael** [caf3babe/car-rental-microservices#35]

**Comment by caf3babe** [comment]
Id go for BigInteger for the simple reason that MongoRepository can handle the ID creation out of the box. Otherwhise we need to implement own logic to generate Ids.

**Comment by caf3babe** [comment]
Or does it break the api? then we should probably consider implementing own id generator or sequence - whatever

**Comment by schneidermichael** [comment]
only for uniformity and the understanding
